[dev]
  command = "npm run dev"
  targetPort = 5174
  framework = "vite"

[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
